export default {
    name:'bestsales',
    title:'Bestsales',
    type:'document',
    fields:[
        {
            name:'image',
            title:'Image',
            type:'array',
            of:[{type:'image'}],
            options:{
                hotspot:true,
            }
        },
        {
            name:'name',
            title:'Name',
            type:'string'
        },
        {
            name:'prerprice',
            title:'Prevprice',
            type:'number'
        },
        {
            name:'price',
            title:'Price',
            type:'number'
        },
        {
            name:'slug',
            title:'Slug',
            type:'slug',
            options : {
                source:'name',
                maxLength: 90
            }
        },
        {
            name:'details',
            title:'Details',
            type:'string'
        }
    ]
}